/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulariojava;

import javax.swing.JOptionPane;



/**
 *
 * @author 1091809
 */
public class PesoPlanetas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PesoPlanetas.class.getName());

    /**
     * Creates new form PesoPlanetas
     */
    public PesoPlanetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btcalculopeso = new javax.swing.JButton();
        jtcaixadedados = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbplanetas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Peso Planetas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btcalculopeso.setText("Calcular Peso");
        btcalculopeso.addActionListener(this::btcalculopesoActionPerformed);

        jtcaixadedados.addActionListener(this::jtcaixadedadosActionPerformed);

        jLabel1.setText("      Peso Na Terra  KG.");

        cbplanetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MERCÚRIO", "VÊNUS", "TERRA", "MARTE", "JÚPITER", "SATURNO", "URANO", "NETUNO", "LUA" }));
        cbplanetas.addActionListener(this::cbplanetasActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("COMPARAÇÃO DE PESOS DE PESSOAS EM PLANETAS DIVERSOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtcaixadedados)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbplanetas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btcalculopeso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtcaixadedados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbplanetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(btcalculopeso)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btcalculopesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcalculopesoActionPerformed
       double quilo = Double.parseDouble(jtcaixadedados.getText());
       String produtoSelecionado = cbplanetas.getSelectedItem().toString();
       
       double gravidade = 0;
       double resultado = 0;
  
       try{
          
           switch(produtoSelecionado){
              
              case "MERCÚRIO":
                  gravidade = 3.6;
                  break;
                  
                  case "VÊNUS":
                  gravidade = 8.7;
                  break;
                  
                  case "TERRA":
                  JOptionPane.showMessageDialog(null, "Seu Peso É:"+quilo);
                  break;
                  
                  case "MARTE":
                  gravidade = 3.7;
                  break;
                  
                  case "JÚPTER":
                  gravidade = 24.79;
                  break;
                  
                  case "SATURNO":
                  gravidade = 10.44;
                  break;
                  
                  case "URANO":
                  gravidade = 8.69;
                  break;
                  
                  case "NETUNO":
                  gravidade = 11.15;
                  break;
                  
                  case "LUA":
                  gravidade = 1.6;
                  break;              
          }
             resultado = quilo / 10 * gravidade;
             JOptionPane.showMessageDialog(null, "O Peso É:" +resultado);
             
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Não Pode Conter Letras Ou Simbolos.");          
       }
       
    }//GEN-LAST:event_btcalculopesoActionPerformed

    private void jtcaixadedadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcaixadedadosActionPerformed
        
    }//GEN-LAST:event_jtcaixadedadosActionPerformed

    private void cbplanetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbplanetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbplanetasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PesoPlanetas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcalculopeso;
    private javax.swing.JComboBox<String> cbplanetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtcaixadedados;
    // End of variables declaration//GEN-END:variables
}
